dist: xenial
language: python

env:
  global:
  - PYTHONUNBUFFERED=1
  - APPVEYOR_SLUG=python-bchlib
  - APPVEYOR_ACCOUNT=jkent
  # APPVEYOR_TOKEN
  - secure: "Abf+IU1bskgna41gmQgpJgMloSSsMc0u5i/b0FLvoMKwOBqL8z/2nmMlw7W8ESycX7ppn9dvWUfdPmqN1FVJR93XETZLr/Zha10U9ry7dVvuGKKnyH0W4jAtigCtLmiGoq98HtNcz3IklB8CNBjp7tc+hOBI78nSwWeo78buLhkaOrSeiN3FUI/AN0O3by6LruIi6OWka7wjxmXoVD1CJPb591plhdDyjxcmd8Mahi4hfTR0n55mCB/S3/RwgvzG8juCqJ+fUGXoaCZwCV/R1seRpPn9KzjnV7X1tTjRNnvo/vyRydncy1/i3UPDsZYMkrG/msqI5eRdALmEjxViTEdYr0UdZq2FQAG9gKWBb8GwZ9MPUy5aezA3MTaThGmYTjP5h6bMAvBGrVAZP1P2FBDgcuPrkHXHd7C5pZTz3mbiIiYNDts8+/JyXnj6RivqeGZm/8540KKSWgFrDfdZCNv6ZOtuZRKkziinkyFDcGEotHQ5apCe2eWKt0XBHX8nqvq+8+UNQ0kqNdBnUnXvdXDq1FAoim9FNji/mvcmocTTZezArDDxDgpzw1AsNGp0ShnUCX/ITKX0fnmIYAWVVetS6bwkC2F3cvycodark2J1EBdWpOzfDpIH30goaTik7Ed4GhoTyJ40wzVIMArz+aT6MatRMBh62kU7s2DaSi8="
  - TWINE_USERNAME=jkent
  # TWINE_PASSWORD
  - secure: "D6Ys7kuB+GCz7vijgSnoga2k9pMFVxsb7Jk4qo4cT+k+sT3Dpo1Y14aNCUVj+cqMn56ebaE6ZRDnYCpI8sk730+8+bLKlVUFWpckE8uSOJnvon5yzUDOwcbdxRoAkEVuYvtGZL1Z25IUN47Ee0reZqCf5B34xDVRcP6UohZaUKC3qoChxirMzf0+cw6CfUQIevk8ItLx2z1E7kk2XB0Y1mb1oK14dHG/e9uHoCKi3gzZluNdv3kOhjpjXZtfkVrMTkXIrU3QChvYT8qJDYUSlnUOD75SqlfnQc+c8bJYQ/iNN9KskQipxIiL7Be07T5shHMga8uPtUUL/4SmBtA6oZTR8H94w8lbYb4D2m35H0j0PU3d+9fR5F90DlsjzTd0LBRcZlaYLfcKSSh2Kr648XOqpMzWnRqB3GsUK0yg4l0g71rm0pHKKwe5TSe8caayVol9Sg84OUQ+ZSMLHAbhbqfMWH859zXjYIxlTR66A7WuIs70sbZPQ1AFf1H5K1LAvYU0wxxClRxlvAyWVQWEVembo6neZZpHqcd85hUP0rTgMw7dH2yhmr1I4v9ule8OVD1aR42/CMH06GVLLF7x9qhHPjQB8BAgMDy7wLXn55g5xpiMZAqK9HG9y4X+HIi4SI9pGlE5vbBGZjl16xTFybeCZx4i3fKHU1QIPFHTLms="
  - AWS_ACCESS_KEY_ID=AKIA5LW6HA4HS6R3LISB
  # AWS_SECRET_ACCESS_KEY
  - secure: "fxco+YDXbqWePOli1ne5yUp1gYqEfbGJ88WktexQ8RR85l3G30T2Pec04eNx0JR8CCBI/ggHs877PYrQ9g/C0elqFRCE3+/bpO79g3p7dLM+cUq6gFDE8EK8A6YXfnC/+hwp37ikWVixq+q9DWykn/YdYZ5wADp3yjkoQmBuHUVe8DSIioBQuY86PSzNeFbDKdVL26JSsTmZSR1z3gdBhXK5jLTNtWb8re0o8MGGhuYX10Dpol1HALkdnDsSAY4ZNyFcYuQx+zPptMsL/tjUyOKzfoXKEti/nuJA/W0j9W8LYEHPe36A3x57qlLk09ax+G1nnAzyBileOzCFx0wnc5D2kW9a/0Em/MsfX1qV9ZAHf+KpZUMkPRZseD0hLPh+6chu0MHGhuzNhxM1QTz5WjyLUhGoAVOxZB+MrEyRr30ml7qcevrWPK0e1Doy466G7FMdc3yi92d+9g2iRDSXf4ztGanThkDy0kejQHLZNm/1xeVK18//KKBxbRX34izcPg9hR3NRl2CAle5ypDE0btfGLtpvssXYZadNjLVQC5B0C8vq0FDjAhnbYrfc3ijn9z9tuhBZxK8uO2A5hJvFpeYfQW4viCrZKiJ4EB46OGPhfsdeuzCutXw+WoXRVBnMzdqB7JjuzwXqH0PSarFKEJxZ6LC3m6RPMrtbbPO5/v4="

stages:
  - name: test
  - name: build sdist
    if: type = push AND tag =~ ^v\d+\.\d+\.\d+ OR branch = testing
  - name: build wheels
    if: type = push AND tag =~ ^v\d+\.\d+\.\d+ OR branch = testing
  - name: deploy to pypi
    if: type = push AND tag =~ ^v\d+\.\d+\.\d+

python:
- '3.6'
- '3.7'
- '3.8'
- '3.9'
- '3.10'

install:
- pip install -e .[test]

script: pytest

jobs:
  fast_finish: true
  include:
  - stage: build sdist
    before_install: &setup_s3
    - pip install awscli
    - mkdir dist
    install: skip
    script: python setup.py sdist
    after_success:
    - aws s3 rm --recursive s3://python-bchlib/dist
    - aws s3 sync dist s3://python-bchlib/dist

  - stage: build wheels
    env: OS=LINUX
    sudo: required
    before_install: *setup_s3
    install: skip
    script: docker run --rm -it -v $(pwd):/io -w /io quay.io/pypa/manylinux1_x86_64 .ci/build_linux_wheels.sh
    after_success: aws s3 sync wheelhouse s3://python-bchlib/dist

  - stage: build wheels
    os: osx
    language: generic
    env: OS=MACOS
    before_install: *setup_s3
    install: skip
    script: .ci/build_macos_wheels.sh
    after_success: aws s3 sync dist s3://python-bchlib/dist

  - stage: build wheels
    env: OS=WINDOWS
    before_install: *setup_s3
    install: pip install requests
    script: .ci/build_windows_wheels.py
    after_success: aws s3 sync wheelhouse s3://python-bchlib/dist

  - stage: deploy to pypi
    before_install: *setup_s3
    install: pip install twine
    script:
    - aws s3 sync s3://python-bchlib/dist dist
    - twine upload dist/*
    - aws s3 rm --recursive s3://python-bchlib/dist
